blog/urls.py
from django.urls import path
from.import views

urlpatterns=[
    path("",views.home,name='home'),
    path('signup', views.signup,name= 'signup'),
    path('signin', views.signin,name= 'signin'),
    path('signout', views.signout,name= 'signout'),
]

blogapp/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('blog.urls')),
    path("mainapp/",include('mainapp.urls')),
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from.import views
app_name='mainapp'
urlpatterns=[
    path("",views.blogs,name='blogs'),
    path("blog/<int:id>/",views.blog,name='blog'),
    path("create_blog",views.create_blog,name='create_blog'),
    path("searchblog",views.searchblog,name='searchblog'),
    path("profile/<int:pk>/",views.profile,name='profile'),
    path("editblog/<int:pk>/",views.editblog,name='editblog'),
    path("deleteblog/<int:pk>/",views.deleteblog,name='deleteblog'),
    path("updateprofile",views.updateprofile,name='updateprofile'),
]

blog/models.py
from django.db import models

# Create your models here.

mainapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save




class Profiles(models.Model):
    GENDER_CHOICES=[
        ('Male','Male'),
        ('Female','Female'),
        ('Other','Other'),
    ]
    user=models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    phone=models.IntegerField(blank=True,null=True)
    Avatar=models.ImageField(default='default_pic.jpg', blank=True, null=True)
    location=models.CharField(max_length=20,blank=True, null=True)
    gender=models.CharField(max_length=6, choices=GENDER_CHOICES,default='Male')
    bio=models.TextField(blank=True, null=True)
    date_joined=models.DateTimeField(auto_now_add=True)
    follows=models.ManyToManyField('self',related_name='followed_by', symmetrical=False,blank=True)
    def __str__(self):
        return self.user.username

def create_profile(sender,instance,created,**kwargs):
    if created:
        user_profile=Profiles(user=instance)
        user_profile.save()
        user_profile.follows.set([instance.profiles.id])
        user_profile.save()
post_save.connect(create_profile,sender=User)


class Blogs(models.Model):
    
    user=models.ForeignKey(User,related_name="posts",null=True, on_delete=models.DO_NOTHING)
    post=models.TextField(blank=True, null=True)
    date_created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user)



    
#python manage.py runserver
#python manage.py makemigrations
#python manage.py migrate

mainapp/forms.py
from django.forms import ModelForm
from.models import Profiles,Blogs
from django import forms

class ProfileForm(ModelForm):
    class Meta:
        model=Profiles
        fields='__all__'
        exclude=['user']


class PostForm(forms.ModelForm):
    # post=forms.TextInput()
    class Meta:
        model=Blogs
        fields=['post']
        exclude=('user',)

class EditForm(forms.ModelForm):
    class Meta:
        model=Blogs
        fields=['post']

blog/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from.form import signupForm

# Create your views here.
def home(request):
    return render(request, 'blog/home.html')


def signup(request):
    if request.method=='POST':
        signupform=signupForm(request.POST)
        if signupform.is_valid():
            signupform.save()
            messages.success(request, 'account successfully created')
            return redirect('signin')
    else:
        signupform=signupForm()
    return render(request, 'blog/register.html',{"form":signupform})

def signin(request):
    if request.method=='POST':
        signinform=AuthenticationForm(data=request.POST)
        if signinform.is_valid():
            
            login(request, signinform.get_user())
            messages.success(request, 'you successfully logged in')
            return redirect('home')
            
    else:
        signinform=AuthenticationForm()
    return render(request, 'blog/login.html',{"form":signinform})

def signout(request):
    logout(request)
    messages.success(request, 'you successfully logged out')
    return redirect('home')

mainapp/views.py
from django.shortcuts import render,redirect
from.forms import ProfileForm,PostForm,EditForm
from django.contrib.auth.models import User
from.models import Profiles,Blogs

def blogs(request):
    posts=Blogs.objects.all().order_by("-date_created")
    context={
        "posts":posts
    }
    return render(request, 'app/blogs.html',context)

def create_blog(request):
    form=PostForm()
    if request.method=='POST':
       form=PostForm(request.POST) 
       if form.is_valid():
           instance=form.save(commit=False)
           instance.user=request.user
           instance.save()
           return redirect('mainapp:blogs')
    context={
        'form':form        
        }
    return render(request, 'app/createblog.html',context)

def blog(request, id):
    post=Blogs.objects.get(id=id)
    context={
        "post":post
    }
    return render(request, 'app/blog.html',context)
def editblog(request,pk):
    post=Blogs.objects.get(id=pk)
    if request.method=='POST':
        form=EditForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('mainapp:blog',id=post.id)
    else:
        form=EditForm(instance=post)
    context={
        'form':form,
        'post':post
    }
    return render(request, 'app/editblog.html', context)

def deleteblog(request,pk):
    post=Blogs.objects.get(id=pk)
    post.delete()
    return redirect('mainapp:blogs')


def searchblog(request):
    if request.method=='POST':
        search=request.POST['search']
        post_searched=Blogs.objects.filter(post__contains=search).order_by("-date_created")
        # return redirect("mainapp:searchblog")
    
        context={
            'post_searched':post_searched,
            'searche':search,
        }
    return render(request, 'app/search.html', context)


def profile(request,pk):
    # if request.user.is_authenticated:
    profile=Profiles.objects.get(user_id=pk)
    if request.method=='POST':
        current_user=request.user.profiles
        action = request.POST["follows"]
        if action=='unfollows':
            current_user.follows.remove(profile)
        elif  action=='follow':
            current_user.follows.add(profile)
    try:
        profile=Profiles.objects.get(user_id=pk)
        blogs=Blogs.objects.filter(user_id=pk)
        
    except Profiles.DoesNotExist:
        return render(request,'app/error.html',{'message':"doesn't exist"})
    context={
        'profile':profile,
        'blogs':blogs
    }
    return render(request, 'app/profile.html',context)


def updateprofile(request):
    user=request.user.profiles
    profform=ProfileForm(instance=user)
    if request.method=='POST':
        profform=ProfileForm( request.POST, request.FILES, instance=user)
        if profform.is_valid():
            profform.save()
            return redirect('home')
    else:
        profform=ProfileForm(instance=user)
    return render(request, 'app/updateprofile.html',{'form':profform})


#python manage.py runserver
#python manage.py makemigrations
#python manage.py migrate

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BlogApp|{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    {% block extra_css %}{% endblock %}
</head>
<body>
 
    {% block content %}
    {% endblock %}

</body>
</html>

blog/templates/blog/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>HomePage</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>
<body>
    <header class="navbar">
        <div class="container">
            <h1>Welcome {{request.user.username}}</h1>
            <nav>
                <ul>
                    {% if request.user.is_authenticated %}
                    <li><a href="{% url 'mainapp:profile' request.user.id %}">view profile</a></li>
                    <li><a href="{% url 'mainapp:blogs' %}">Blogs</a></li>
                    <li class="logout">
                        <a href="{% url 'signout' %}">Logout <br>
                            <span>{{request.user.username}}</span></a>
                        <img src="{{request.user.profiles.Avatar.url}}" alt="User Profile Picture" class="profile-pic">
                    </li>

                    {% else %}
                    <li><a href="{% url 'signup' %}">Register</a></li>
                    <li><a href="{% url 'signin' %}">Login</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </header>
    <!-- Hero Section -->
    <section class="hero">
        <div class="container">
            <h1>Hi, {{request.user.username}}</h1>
            <p>welcome to our blog app ' like a twitter clone'</p>
            <a href="#contact" class="btn">Get in Touch</a>
            <a href="#portfolio" class="btn">View My Work</a>
        </div>
    </section>

    <!-- About Me Section -->
    <section id="about" class="about">
        <div class="container">
            <h2>About</h2>
            <p>
                In this webapp, you can create a blog post and post it on this platform, Also make sure you create complete updating your profile by visiting those pages from the links on the top of this page.
            </p>
        </div>
    </section>

    
    <section id="portfolio" class="portfolio">
        <div class="container">
            <h2>My Recent Work</h2>
            <p>Check out some of my projects on GitHub or view my resume.</p>
            <a href="https://github.com/yourgithub" class="btn">GitHub</a>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="contact">
        <div class="container">
            <h2>Let’s Connect!</h2>
            <p>You can reach me at:</p>
            <p>Email: <a href="mailto:samgachoya9@gmail.com">samgachoya9@gmail.com</a></p>
            <p>Phone: 0768052814</p>
            <p>Or find me on <a href="https://www.linkedin.com">LinkedIn</a></p>
        </div>
    </section>

    <!-- Footer -->
    <footer class="footer">
        <div class="container">
            <p>&copy; 2024 Samuel Gachoya. All Rights Reserved.</p>
        </div>
    </footer>
</body>
</html>

blog/templates/blog/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LoginPage</title>
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
</head>
<body>
    <style>
        .fieldd {background: rgb(255, 255, 255);}
        .errorlist li{color: red;}
        .errorlist li::marker{content: '🚨';}
        .helptext{display: block;
        color: rgb(28, 31, 28);}
        .box{box-shadow: 1px 0px 2px rgb(191, 191, 224);
        
    padding: 50px;
    width: 90%;}
        </style>
    <form action="{% url 'signin' %}" class="form" method="post">
        <h2 class="title">login</h2>
        {% for message in messages %}
        {{message.message}}
        {% endfor %}
        {% csrf_token %}
        {{ form.as_p}}
        
        <button class="btn">Login</button>
        <p>if you don't have an account,<a class="link" href="{% url 'signup' %}">Register</a></p>
        <p>if you forgot password<a class="link" href="">Reset Password</a></p>
    </form>
    
</body>
</html>

blog/templates/blog/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-DyZvI8X5tDkG1w7c2cDgOb6FY2Jq6+0cN8U5xPU78YYe3U0K+B6X2IzjQl9C7l9q" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-1R0XeWmCymg0V4S/9gXEG48r18d3iF4ZbsIb4g8IB4EGBvUj8cQp8DeT4AZhShp5" crossorigin="anonymous"></script>

</head>
<body>
    
    
    <style>
        .fieldd {background: rgb(255, 255, 255);}
        .errorlist li{color: red;}
        .errorlist li::marker{content: '🚨';}
        .helptext{display: block;
        color: rgb(28, 31, 28);}
        .box{box-shadow: 1px 0px 2px rgb(191, 191, 224);
        
    padding: 50px;
    width: 90%;}
    
    </style>
    <form action="{% url 'signup' %}" class="form" method="post">
        <h2 class="title">sign up</h2>
        {% for message in messages %}
        {{message}}
        {% endfor %}
        {% csrf_token %}
        {{ form.as_p}}
        
        <button class="btn">signup</button>
        <p>if you already have an account,<a class="link" href="{% url 'signin' %}">login</a></p>
    
        
    </form>
</body>
</html>

mainapp/templates/app/blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>
    <nav>
        <h2>Post</h2>
     <a href="{% url 'mainapp:blogs' %}">Back to blogs</a>
    </nav>
    
    <div class="blog">
        <div class="title">
            <p>
                <a href="{% url 'mainapp:profile' post.user.id %}">@{{post.user.username}}</a>
            </p>
                <a href="{% url 'mainapp:profile' post.user.id %}"><img src="{{post.user.profiles.Avatar.url}}" alt="{{post.user.username}}" class="profile-pic"></a>
                         
        </div>
        <div class="body">
            <div class="btns">
                <a href="{% url 'mainapp:deleteblog' post.id %}" class="btn">Delete</a>
                <a href="{% url 'mainapp:editblog' post.id %}" class="btn">Edit</a>
             </div>
            <p>{{post.post}}</p>
            <hr class="line">
            
            <p class="date">{{post.date_created}}</p>
            <hr>
        </div>
        
    </div>
</body>
</html>

mainapp/templates/app/blogs.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BlogsPage</title>
    <link rel="stylesheet" href="{% static 'css/blogs.css' %}">
</head>
<body>
    <nav>
        <a class="home-btn" href="{% url 'home' %}">Home</a>
        <!-- <a href="{% url 'mainapp:create_blog' %}">create</a> -->
        <form action="{% url 'mainapp:searchblog' %}" method="post">
            {% csrf_token %}
            <input type="text" name="search" id="">
            <button>Search</button>
        </form>
    </nav>
    
    <div class="blogs_body">
        {% if posts %}
        {% load blog_extras %}
       
            {% for post in posts %}
             
            <div class="blog_body">
                <div class="title">
                    <a href="{% url 'mainapp:profile' post.user.id %}" class="user">@{{post.user.username}}</a>
                    <img src="{{post.user.profiles.Avatar.url}}" alt="User Profile Picture" class="profile-pic">
                    
                </div>
                
                <div class="body">
                    <div class="post-cover">
                        {% if post.post|length > 200%}
                        <a href="{% url 'mainapp:blog' post.id %}" class="post">
                            {{post.post| truncate_chars:200 }}   
                            <p class="create"><a href="{% url 'mainapp:create_blog' %}">+</a></p>
                            
                        </a>
                        <p><a href="{% url 'mainapp:blog' post.id %}">Read more</a></p>
                        {% else %}
                        <a href="{% url 'mainapp:blog' post.id %}" class="post">
                            {{post.post}}   
                            <p class="create"><a href="{% url 'mainapp:create_blog' %}">+</a></p>
                            
                        </a>
                        {% endif %}
                    </div>
                    <p class="date">{{post.date_created}}</p>
                </div>
                
            </div>
            
            
            <hr>
            {% endfor %}
        {% else %}
            <p>No blog created</p>
            <p class="create"><a href="{% url 'mainapp:create_blog' %}">+</a></p>
        {% endif %}
        
        
    </div>
</body>
</html>

mainapp/templates/app/createblog.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/update.css' %}">
</head>
<body>
   <a href="{% url 'mainapp:blogs' %}">back to blogs</a>
    <h3>Post</h3>

    <form action="{% url 'mainapp:create_blog' %}" method="post">
        {% csrf_token %}
        {{form}}
        <input  class="btn" type="submit">

    </form>
</body>
</html>

mainapp/templates/app/editblog.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Blog</title>
    <link rel="stylesheet" href="{% static 'css/update.css' %}">
</head>
<body>
    
    <form class="form" action="{% url 'mainapp:editblog' post.id %}" method="post">
        {% csrf_token %}
        <!-- {{form}} -->
        
            <p class="post">{{form.post}}</p>
        <input type="submit" class="btn"  value="edit">
    </form>
</body>
</html>

mainapp/templates/app/error.html
{{message}}

mainapp/templates/app/followers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Followers</title>
</head>
<body>
    <p>{% for following in profile.follows.all %} {{following}} {% endfor %}</p>
</body>
</html>

mainapp/templates/app/profile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ProfilePage</title>
    <link rel="stylesheet" href="{% static 'css/profile.css' %}" />
  </head>
  {% if profile %}
  <body>
    <!-- <img src="{{request.user.profiles.Avatar.url}}" width="40px"> -->

    <header>
      <div class="container">
        <div class="header-content">
          <h1>Profile</h1>
          <nav>
            <ul>
              <li><a href="/">Home</a></li>
              <li><a href="{% url 'mainapp:blogs' %}">Blogs</a></li>
              <!-- <li><a href="/notifications">Notifications</a></li> -->
              <!-- <li><a href="/messages">Messages</a></li> -->
              {% if request.user.id == profile.user.id %}
              <li>
                <a href="{% url 'mainapp:updateprofile'  %}">Update Profile</a>
              </li>
              {% endif %}
            </ul>
          </nav>
        </div>
      </div>
    </header>

    <section class="profile-banner">
      <div class="container">
        <h1>{{profile.user.username}}'s Profile</h1>
        <div class="banner-img"></div>
        <div class="profile-info">
          <img
            src="{{profile.Avatar.url}}"
            alt="User Profile Picture"
            class="profile-pic"
          />
          <div class="profile-details">
            <p>Username:{{profile.user}}</p>
            <div>
              <p><strong>Email: </strong>{{profile.user.email}}</p>
            </div>

            <p><strong>Country: </strong>{{profile.location}}</p>
            <p><strong>Gender:</strong>{{profile.gender}}</p>
            <p class="bio"><strong>Bio: </strong>{{profile.bio}}</p>
            <p><strong>Joined: </strong>{{profile.date_joined}}</p>
            <form method="post">
              {% csrf_token %} 
              {% if profile in user.profiles.follows.all %}
              <button class="follow-btn" name="follows" value="follow">
                follow
              </button>
              {% else %}
              <button class="follow-btn" name="unfollow">unFollow.</button>
              {% endif %}
            </form>
          </div>
        </div>
      </div>
    </section>

    <section class="profile-nav">
      <div class="container">
        <ul>
          <li><a href="# posts">Posts</a></li>
          <li><a href="#followers">Followers</a></li>
          <li><a href="#">Likes</a></li>
        </ul>
      </div>
    </section>
    <section id="followers" class="followers">
      <ul>
        <li>
          {% for following in profile.follows.all %} {{following}} {% endfor %}
        </li>
      </ul>
    </section>

    <section id="posts" class="profile-timeline posts">
      <div class="container">
        {% if blogs %} {% for blog in blogs %}

        <div class="post">
          <h4><a href="#">{{profile.user.username}}'s Profile's Posts</a></h4>
          <p>Posted on: {{blog.date_created}}</p>
          <p>{{blog.post}}.</p>
        </div>
        {% endfor %} {% else %} NO POSTS {% endif %}

        
      </div>
    </section>

    <footer>
      <div class="container">
        <p>&copy; 2024 Blog App. All rights reserved.</p>
      </div>
    </footer>
  </body>
  {% endif %}
</html>

mainapp/templates/app/search.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Results</title>
    <link rel="stylesheet" href="{% static 'css/blogs.css' %}">
</head>
<body>
    <nav>
        <a href="{% url 'mainapp:blogs' %}">Back to blogs</a>
    </nav>
    <div class="blogs_body">
        {% if searche %}
        {% for post_searched in post_searched %}
            <!-- {{post_searched.post}} -->
            <div class="blog_body">
                <div class="title">
                    <img src="{{post_searched.user.profiles.Avatar.url}}" alt="User Profile Picture" class="profile-pic">
                    <a href="{% url 'mainapp:profile' post_searched.user.id %}" class="user">@{{post_searched.user.username}}</a>
                </div>
                
                <div class="body">
                    <div class="post-cover"><a href="{% url 'mainapp:blog' post_searched.id %}" class="post">{{post_searched.post}}</a></div>
                    <p class="date">{{post_searched.date_created}}</p>
                </div>
                
            </div>
            
        {% endfor %}
        {% else %}
            no such post
    {% endif %}
    </div>
    
</body>
</html>

mainapp/templates/app/updateprofile.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    <link rel="stylesheet" href="{% static 'css/update.css' %}">
</head>
<body>
    
    <nav>
        <h1>
            profile page
            
        </h1>
        <a href="{% url 'mainapp:blogs' %}">Back to blogs</a>
    </nav>
    <img src="{{request.user.profiles.Avatar.url}}" >
    
    

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn" value="update">
    </form>
</body>
</html>